# Generated by Django 4.0.6 on 2022-08-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air_Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('coulor', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400, null=True)),
                ('year', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jordans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('coulor', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400, null=True)),
                ('year', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
    ]
