# Generated by Django 4.0.6 on 2022-08-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_force',
            old_name='coulor',
            new_name='coulor_Air',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='description',
            new_name='description_Air',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='model',
            new_name='model_Air',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='price',
            new_name='price_Air',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='stock',
            new_name='stock_Air',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='year',
            new_name='year_Air',
        ),
    ]
