# Generated by Django 4.0.6 on 2022-08-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_rename_coulor_air_force_coulor_air_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_force',
            old_name='coulor_Air',
            new_name='coulor',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='description_Air',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='model_Air',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='price_Air',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='stock_Air',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='air_force',
            old_name='year_Air',
            new_name='year',
        ),
    ]
