# Generated by Django 4.0.6 on 2022-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_rename_coulor_air_air_force_coulor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_force',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img_produts'),
        ),
    ]
