# Generated by Django 4.0.6 on 2022-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_air_force_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_force',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img_produts/'),
        ),
    ]
