# Generated by Django 4.0.6 on 2022-08-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0006_alter_air_force_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jordans',
            name='img',
            field=models.ImageField(null=True, upload_to='Entrega_Comparada/static/img_produts/'),
        ),
    ]
