# Generated by Django 4.0.6 on 2022-08-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0007_jordans_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=400, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Entrega_Comparada/static/img_produts/')),
            ],
        ),
    ]
