# Generated by Django 4.0.6 on 2022-08-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0008_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_force',
            name='year',
        ),
        migrations.RemoveField(
            model_name='jordans',
            name='year',
        ),
    ]
