# Generated by Django 4.0.6 on 2022-08-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0009_remove_air_force_year_remove_jordans_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_force',
            name='img',
            field=models.ImageField(null=True, upload_to='Air_Force'),
        ),
        migrations.AlterField(
            model_name='jordans',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
