# Generated by Django 4.0.6 on 2022-08-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0010_alter_air_force_img_alter_jordans_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jordans',
            name='img',
            field=models.ImageField(null=True, upload_to='Air_Force'),
        ),
    ]
