# Generated by Django 4.0.6 on 2022-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0011_alter_jordans_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_force',
            name='img',
            field=models.ImageField(null=True, upload_to='Entrega_Comparada/static/img_produts/'),
        ),
        migrations.AlterField(
            model_name='jordans',
            name='img',
            field=models.ImageField(null=True, upload_to='Entrega_Comparada/static/img_produts/'),
        ),
    ]
