# Generated by Django 4.0.6 on 2022-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0012_alter_air_force_img_alter_jordans_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='img',
            field=models.ImageField(null=True, upload_to='img_Accessories/'),
        ),
        migrations.AlterField(
            model_name='air_force',
            name='img',
            field=models.ImageField(null=True, upload_to='img_Air_Force/'),
        ),
        migrations.AlterField(
            model_name='jordans',
            name='img',
            field=models.ImageField(null=True, upload_to='img_Jordan/'),
        ),
    ]
